export const p_data = [
    {name:'T-Z-5',
        id:1,
        size:[
            {id:15,value:'13'},
            {id:16,value:'14'},
            {id:17,value:'15'},
            {id:18,value:'16'},
            {id:19,value:'17'}
        ]},
    {name:'T-Z-6',
        id:2,
        size:[
            {id:25,value:'13'},
            {id:26,value:'14'},
            {id:27,value:'15'},
            {id:28,value:'16'},
            {id:29,value:'17'}
        ]},
    {name:'T-Z-7',
        id:3,
        size:[
            {id:35,value:'13'},
            {id:36,value:'14'},
            {id:37,value:'15'},
            {id:38,value:'16'},
            {id:39,value:'17'}
        ]},
    {name:'T-Z-8',
        id:4,
        size:[
            {id:45,value:'13'},
            {id:46,value:'14'},
            {id:47,value:'15'},
            {id:48,value:'16'},
            {id:49,value:'17'}
        ]},
        {name:'T-C-5',
        id:5,
        size:[
            {id:55,value:'13'},
            {id:56,value:'14'},
            {id:57,value:'15'},
            {id:58,value:'16'},
            {id:59,value:'17'}
        ]},
    {name:'T-C-6',
        id:6,
        size:[
            {id:65,value:'13'},
            {id:66,value:'14'},
            {id:67,value:'15'},
            {id:68,value:'16'},
            {id:69,value:'17'}
        ]},
    {name:'T-C-7',
        id:7,
        size:[
            {id:75,value:'13'},
            {id:76,value:'14'},
            {id:77,value:'15'},
            {id:78,value:'16'},
            {id:79,value:'17'}
        ]},
    {name:'T-C-8',
        id:8,
        size:[
            {id:85,value:'13'},
            {id:86,value:'14'},
            {id:87,value:'15'},
            {id:88,value:'16'},
            {id:89,value:'17'}
        ]},
];